### ISSUE TITLE
cannot join developer chat on gitter without giving up civil rights

### ISSUE THREAD

**Issue by sneak** [quorumcontrol/dgit#44]
From GitLab's Gitter TOS:

> Any dispute, controversy or claim arising out of or relating to this Agreement, including the formation, interpretation, breach or termination thereof, including whether the claims asserted are arbitrable, which has not been resolved via the process laid out in Dispute resolution will then be referred to and finally determined by arbitration in accordance with the Arbitration Rules of the Netherlands Arbitration Institute. The arbitral tribunal shall be composed of one arbitrator. The place of arbitration shall be Utrecht or Amsterdam, The Netherlands. The arbitral procedure shall be conducted in the English language. Judgment upon the award rendered by the arbitrator(s) may be entered in any court having jurisdiction thereof.

Requiring your community to give up their civil rights as a prerequisite to participation by demanding that they enter into a large and abusive legal contract with a third party is not befitting an organization that promotes decentralization.

May I suggest a self-hosted Mattermost?  I'd be happy to run/admin one for your project if you'd like.

**Comment by bqv** [comment]
I would favour matrix

**Comment by cap10morgan** [comment]
There is a Matrix mirror of the Gitter channel available at `#gitter_quorumcontrol-dgit=2Fcommunity:matrix.org` for anyone else with similar concerns.
