### ISSUE TITLE
dgit init commands gives : "Error with keyring: Specified keyring backend not available" on WSL 1

### ISSUE THREAD

**Issue by chelneru** [quorumcontrol/dgit#51]
Hello,
I wanted to play a bit with dgit to see how it is.

I have created an empty repo with `git init`. I added a file and committed it.  
Then I used `dgit init` and got the aforementioned error message 
`Error with keyring: Specified keyring backend not available`.

I also tried to clone an existing repo and to run `dgit init` inside it but I got the same error.

I am using dgit version v0.0.11-alpha

**Comment by cap10morgan** [comment]
Thanks for the report @chelneru, and sorry to hear you ran into an error. Can you give us some more details about what platform and version you're running on (e.g. macOS 10.15 or Linux distribution version X), git version, shell and version, etc.?

**Comment by cap10morgan** [comment]
Oh, sorry, I just noticed you included "WSL 1" in the title. That is Windows Subsystem for Linux 1, yes? We haven't tested it on that platform much yet.

**Comment by chelneru** [comment]
Thanks for reply I will try it on a standalone Linux Distribution :)

**Comment by c-nv-s** [comment]
> Oh, sorry, I just noticed you included "WSL 1" in the title. That is Windows Subsystem for Linux 1, yes? We haven't tested it on that platform much yet.

also receiving this same error with both the arm6 and arm7 binaries. testing on Armbian Ubuntu 18.04
$ uname -a
Linux dgit 5.1.12-sunxi #5.90 SMP Fri Jun 28 19:16:14 CEST 2019 armv7l armv7l armv7l GNU/Linux

**Comment by cap10morgan** [comment]
@c-nv-s We are using a library called [keyring](https://github.com/99designs/keyring) to provide secure key storage. Do you have one of the [supported Linux backends](https://github.com/quorumcontrol/dgit/blob/7ef917916c2feabdc5fda10ccdfed866359b7932/keyring/keyring.go#L19) installed?

**Comment by c-nv-s** [comment]
> @c-nv-s We are using a library called [keyring](https://github.com/99designs/keyring) to provide secure key storage. Do you have one of the [supported Linux backends](https://github.com/quorumcontrol/dgit/blob/7ef917916c2feabdc5fda10ccdfed866359b7932/keyring/keyring.go#L19) installed?

I installed gpg2 and pass, generated keys with a [bit of troubleshooting](https://d.sb/2016/11/gpg-inappropriate-ioctl-for-device-errors) due to running within a container, and then ran 'pass init' inside the repo folder before I could run 'dgit init' in the repo folder. Now it seems to be working.

Would probably be useful either adding the list of possible backends to a short 'Requirements' section on the main README.md. Or perhaps some general indication of the necessary commands needed to be run prior to the 'dgit init' command in the Usage section.

Thanks for the great work

**Comment by cap10morgan** [comment]
@c-nv-s Thank you for your interest and feedback!

I totally agree that it would be useful to document the Linux keyring options / prereqs. I've created a new issue for that here: Public issue: https://github.com/quorumcontrol/dgit/issues/72.

**Comment by cap10morgan** [comment]
I believe that installing a supported keyring backend (#72 is about documenting that) will solve this issue, but feel free to reopen if not.
